example:
  enabled: false
  image:
    repository: gcr.io/jenkinsxio/jx-kh-check
    tag: 0.0.54
  runInterval: 30s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"

jxWebhooks:
  enabled: false
  image:
    repository: gcr.io/jenkinsxio/jx-kh-check
    tag: 0.0.54
  runInterval: 90s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"

jxWebhookEvents:
  enabled: true
  image:
    repository: gcr.io/jenkinsxio/jx-kh-check
    tag: 0.0.54
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"

jxInstall:
  enabled: false
  image:
    repository: gcr.io/jenkinsxio/jx-kh-check
    tag: 0.0.54
  runInterval: 90s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"

jxBotToken:
  enabled: false
  image:
    repository: gcr.io/jenkinsxio/jx-kh-check
    tag: 0.0.54
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  gitProvider:

jxPodStatus:
  enabled: false
  image:
    repository: gcr.io/jenkinsxio/jx-kh-check
    tag: 0.0.54
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 15m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  cluster:
    enabled: false

jxSecrets:
  enabled: false
  image:
    repository: gcr.io/jenkinsxio/jx-kh-check
    tag: 0.0.54
  runInterval: 60s # The interval that Kuberhealthy will run your check on
  timeout: 5m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  cluster:
    enabled: false