apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - image: rawlingsj80/jx-release-version:wip2
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            # sleep infinity
            jx-release-version --tag > VERSION
          env:
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: tekton-git
                key: password
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: tekton-git
                key: username
        - name: jx-variables
          resources: {}
        - image: golang:1.15
          name: release-binary
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            make release
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-and-push-image
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json

            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source/cmd/jx-bot-token --dockerfile=/workspace/source/cmd/jx-bot-token/Dockerfile --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-bot-token:$VERSION
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source/cmd/jx-install --dockerfile=/workspace/source/cmd/jx-install/Dockerfile  --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-install:$VERSION
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source/cmd/jx-pod-status --dockerfile=/workspace/source/cmd/jx-pod-status/Dockerfile --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-pod-status:$VERSION
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source/cmd/jx-secrets --dockerfile=/workspace/source/cmd/jx-secrets/Dockerfile --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-secrets:$VERSION
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source/cmd/jx-webhooks --dockerfile=/workspace/source/cmd/jx-webhooks/Dockerfile --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-webhooks:$VERSION
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source/cmd/jx-webhook-events --dockerfile=/workspace/source/cmd/jx-webhook-events/Dockerfile --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-webhook-events:$VERSION
        - name: chart-docs
          resources: {}
        - name: release-chart
          resources: {}
        - name: changelog
          resources: {}
        - name: promote-release
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
